# Generated by Django 5.0.1 on 2024-01-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=20)),
                ('email1', models.EmailField(max_length=254)),
                ('phonenumber1', models.IntegerField()),
                ('password1', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=200)),
            ],
        ),
    ]
