# Generated by Django 5.0.1 on 2024-01-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookname', models.CharField(max_length=20)),
                ('Image', models.ImageField(null=True, upload_to='image')),
                ('Description', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
