# Generated by Django 5.0.1 on 2024-01-24 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username2', models.CharField(max_length=20)),
                ('Email2', models.EmailField(max_length=254)),
                ('Phonenumber2', models.IntegerField()),
                ('Password2', models.CharField(max_length=20)),
                ('Address2', models.CharField(max_length=200)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
