# Generated by Django 5.0.1 on 2024-01-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tutor_demorequest_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='parent_email',
            new_name='parentemail1',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='parent_name',
            new_name='parentname1',
        ),
    ]
