# Generated by Django 5.0.1 on 2024-01-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_parent_email_booking_parentemail1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='select_tutor',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='demorequest',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='demorequest',
            name='confirmed',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
