# Generated by Django 5.0.1 on 2024-01-25 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_teacher2'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher2'),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher2'),
        ),
        migrations.AddField(
            model_name='select_tutor',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher2'),
        ),
    ]
