# Generated by Django 5.0.1 on 2024-01-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_booking_teacher_demorequest_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher2',
            name='availability5',
        ),
        migrations.DeleteModel(
            name='select_tutor',
        ),
    ]
