# Generated by Django 5.0.1 on 2024-01-25 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_teacher2_availability5_delete_select_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability5', models.CharField(max_length=200)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher2')),
            ],
        ),
    ]
