# Generated by Django 5.0.1 on 2024-01-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_tutorlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorlist',
        ),
    ]
