# Generated by Django 5.0.1 on 2024-01-25 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_tutorlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username5', models.CharField(max_length=20)),
                ('email5', models.EmailField(max_length=254)),
                ('password5', models.CharField(max_length=20)),
                ('subject5', models.CharField(max_length=200)),
                ('location5', models.CharField(max_length=100)),
                ('availability6', models.CharField(max_length=200)),
                ('online_available5', models.BooleanField(default=False)),
                ('offline_available5', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher3'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher3'),
        ),
        migrations.DeleteModel(
            name='Teacher2',
        ),
    ]
