# Generated by Django 5.0.1 on 2024-01-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_teacher3_alter_booking_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='parentname1',
            new_name='teachername1',
        ),
    ]
