# Generated by Django 5.0.1 on 2024-01-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_parentname1_booking_teachername1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='teachername1',
            new_name='parentname1',
        ),
    ]
