# Generated by Django 5.0.1 on 2024-01-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_teachername1_booking_parentname1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='parentemail1',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='parentname1',
        ),
    ]
