# Generated by Django 5.0.1 on 2024-01-27 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_booking_parentemail1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type1', models.CharField(max_length=10)),
                ('booking_time1', models.IntegerField()),
                ('booked_datetime', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher3')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
