# Generated by Django 5.0.1 on 2024-01-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_booking1_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking1',
            name='booking_time1',
            field=models.TimeField(),
        ),
    ]
