# Generated by Django 5.0.1 on 2024-01-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_booking1_booking_time1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking1',
            name='booking_time1',
            field=models.CharField(max_length=100),
        ),
    ]
