# Generated by Django 5.0.1 on 2024-01-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_booking1_booking_time1'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking1',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
