# Generated by Django 5.0.1 on 2024-01-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_booking1_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking1',
            name='teacher',
        ),
    ]
