# Generated by Django 5.0.1 on 2024-01-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_booking1_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher3',
            name='availability6',
        ),
        migrations.RemoveField(
            model_name='teacher3',
            name='offline_available5',
        ),
        migrations.RemoveField(
            model_name='teacher3',
            name='online_available5',
        ),
        migrations.DeleteModel(
            name='DemoRequest',
        ),
    ]
