# Generated by Django 5.0.1 on 2024-01-27 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_teacher3_availability6_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestdemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(null=True, upload_to='videos')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.parent')),
            ],
        ),
    ]
