# Generated by Django 5.0.1 on 2024-01-29 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_requestdemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher3',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
