# Generated by Django 5.0.1 on 2024-01-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_teacher3_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking1',
            name='parent',
        ),
    ]
