# Generated by Django 5.0.1 on 2024-01-29 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_booking1_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking1',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.parent'),
        ),
    ]
