# Generated by Django 5.0.1 on 2024-01-29 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_booking1_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdemo',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='requestdemo',
            name='status',
        ),
        migrations.AddField(
            model_name='requestdemo',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.booking1'),
        ),
        migrations.AddField(
            model_name='requestdemo',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requestdemo',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher3'),
        ),
    ]
