# Generated by Django 5.0.1 on 2024-01-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_requestdemo_parent_remove_requestdemo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdemo',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
