# Generated by Django 5.0.1 on 2024-02-05 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_requestdemo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderemail', models.CharField(blank=True, max_length=300, null=True)),
                ('reciveremail', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.CharField(max_length=300, null=True)),
                ('type', models.CharField(max_length=300, null=True)),
                ('message', models.CharField(max_length=300, null=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher3')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.parent')),
            ],
        ),
    ]
