# Generated by Django 5.0.1 on 2024-02-06 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking1',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
    ]
