# Generated by Django 5.0.1 on 2024-02-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_booking1_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher3',
            name='fee',
            field=models.IntegerField(null=True),
        ),
    ]
