# Generated by Django 5.0.1 on 2024-02-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_book_subject1_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher3',
            name='average_rating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='teacher3',
            name='reviews_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
