# Generated by Django 5.0.1 on 2024-02-12 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_book_id_alter_booking1_id_alter_login_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher3'),
        ),
    ]
